# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 13:36
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20171208_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='albums', verbose_name='Заголовок'),
        ),
    ]
