# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_album_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='album',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='height',
            field=models.IntegerField(default=0, help_text='По умолчанию - адаптивно', verbose_name='Высонта'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='albums', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='width',
            field=models.IntegerField(default=0, help_text='По умолчанию - адаптивно', verbose_name='Ширина'),
        ),
    ]
