# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20171209_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_images',
            field=models.ManyToManyField(related_name='album_images', to='album.AlbumImage', verbose_name='Изображения альбома'),
        ),
    ]
