# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20171209_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_images',
        ),
    ]
